country="bangladesh"
print(country)
country="muslim"
print(country)
country="bangladesh"+"muslim"
print(country)
print(country.find("muslim"))
print(country.__len__())
print(len(country))
country.replace('bangladesh','Bangladesh')
print(country)
new_country=country.replace('b','B')
print(new_country)
